### ISSUE TITLE
Unfamiliar options

### ISSUE THREAD

**Issue by jdsteinbach** [evolution/wordpress#116]
Wasn't sure what to do with the following options in yeoman generator. 
```
? New Relic license key (leave blank to disable)
? Datadog license key (leave blank to disable)
? Optional features apache-prefork - Dynamic Apache performance tuning, varnis
h        - High-performance reverse-proxy cache, mail           - Ability to s
end e-mails from the server (i.e. PHP), firewall       - Simple intrusion prot
ection via Fail2ban + iptables, debug          - Tools to monitor processes &
debug when on the server
```

Would be great if they were documented in `TUTORIAL-NEW.md` or `TUTORIAL-CLONE.md`

**Comment by EvanK** [comment]
I've documented the datadog item (and others are already documented) here:

> https://github.com/evolution/wordpress/blob/master/docs/REF-generator-prompts.md
