### ISSUE TITLE
wget fails to fetch kernel purging script

### ISSUE THREAD

**Issue by zuzust** [evolution/wordpress#117]
Provision fails when trying to resolve host address `raw.githubusercontent.com`. See attached image:

![evolution-117](https://cloud.githubusercontent.com/assets/351530/14316497/9460af38-fc03-11e5-83a4-2828fdff1d43.png)

**Comment by EvanK** [comment]
This would indicate a dns issue on either the machine running ansible (your host) or the machine being provisioned (your vm) -- unless it coincided with [Github's downtime yesterday](https://status.github.com/messages), in which case you should try it again.

If you are unable to reach github, you'll see other failures in provisioning and deployment...this is most definitely _a networking issue_ beyond the scope of this project.

I'd suggest you work around any firewalls on your host machine, and ensure that you can resolve the hostname in question at a lower level **on both physical and virtual** machines:

```
    # test dns resolution
    dig raw.githubusercontent.com
    # test whether remote server responds to icmp ping
    ping -c 5 raw.githubusercontent.com
    # diagnose the route of packets to the remote server
    traceroute raw.githubusercontent.com
```

**Comment by zuzust** [comment]
@EvanK, It's been a couple of weeks since I first came across this issue.
Disabling my host firewall do nothing, as you can see below:

![evolution-117-02](https://cloud.githubusercontent.com/assets/351530/14375489/f2401f9e-fd61-11e5-987b-c1f64b1a4fb1.png)

However, something is wrong with the vm's default config, look at the ping output:

![evolution-117-03](https://cloud.githubusercontent.com/assets/351530/14375591/b5c7f0d6-fd62-11e5-89e5-3fc2e547d267.png)

I would like to try with a tested vagrant box. Which version of *ubuntu/trusty64* box do you use?

**Comment by EvanK** [comment]
I've tested this just now with boxes:
* 20160318.0.0
* 20160323.1.0

And evolution versions:
* 1.3.5
* 1.3.9
* 1.3.11

This is definitely a dns failure, possibly at a nameserver level:

> https://lists.isc.org/pipermail/bind-users/2013-November/091921.html

You could try different nameservers for your host and guest machines, [as described in Ubuntu's docs](https://help.ubuntu.com/14.04/serverguide/network-configuration.html#dns-client-configuration). I'd suggest Google's public dns: `8.8.8.8` and `8.8.4.4`

If you do this on the guest machine, you can re-run provisioning afterward: `vagrant provision`

**Comment by EvanK** [comment]
FWIW, I've added provisioning for Google's public nameservers to the [`117-set-nameservers` branch](https://github.com/evolution/wordpress/compare/117-set-nameservers), for experimentation

**Comment by zuzust** [comment]
@EvanK it now works, thanks for the workaround!
