### ISSUE TITLE
Include file paths not resolving as expected

### ISSUE THREAD

**Issue by weeirishman** [evolution/wordpress#131]
`include '/vagrant/web/wp-content/index.php';` from `/vagrant//web/wp-content/themes/twentyfifteen/functions.php`:

Warning: include(/vagrant/web/wp-content/index.php): failed to open stream: No such file or directory in /vagrant/web/wp-content/themes/twentyfifteen/functions.php on line 34

The same line works as expected on Genesis.

**Comment by EvanK** [comment]
Is this a customized `twentyfifteen` theme? I don't see any includes/requires of that file [in the canonical version of said theme](https://github.com/WordPress/WordPress/blob/20b329ba0802183c33d013079957e6e1059ac81b/wp-content/themes/twentyfifteen/functions.php).

Further, I'm not sure _why_ it would be including that particular file, as [it's basically an _empty_ php file](https://github.com/WordPress/WordPress/blob/20b329ba0802183c33d013079957e6e1059ac81b/wp-content/index.php).

That all said, I can get the generator to add an empty `index.php` without much fuss. PR incoming shortly

**Comment by weeirishman** [comment]
No the example is just a demo - I can't get _any_ file to include from the the theme...

**Comment by weeirishman** [comment]
Update - I can get it to work using `__DIR__` and concatenating to that like so:

`include __DIR__ .'/../../plugins/my-plugin/index.php';`

But not an absolute path.

**Comment by EvanK** [comment]
I suspect this is because we're keeping the core wordpress files in a separate (bower-managed) directory, sandboxed away from the actual themes and plugins:

```
. <- project root
└── web
    ├── bower_components
    ├── index.php
    ├── no_robots.txt
    ├── robots.txt
    ├── wp <- wordpress core files, not modified nor versioned in the evolution project
    ├── wp-config.php
    └── wp-content
        ├── mu-plugins
        ├── plugins <- plugins get installed here
        ├── themes <- themes get installed here
        └── uploads
```

You may want to avoid hand-coded include paths, in favor of constants:
* `ABSPATH` - The core wordpress files, untouched and unversioned by us
* `WP_CONTENT_DIR` - The location of installed themes and plugins

Note to self, this should be **prominently documented** in the readme or FAQ

**Comment by weeirishman** [comment]
Makes sense, using `WP_PLUGIN_DIR` got me to the right place.

**Comment by EvanK** [comment]
This is [now documented](https://github.com/evolution/wordpress/blob/e4747d338ca3ad1be95ffc7e5729547bf0229e07/docs/REF-caveats-constants.md), so closing out
