### ISSUE TITLE
WP_Widget error out on `bundle exec cap staging evolve:up:db`

### ISSUE THREAD

**Issue by jasoncomes** [evolution/wordpress#134]
```
DEBUG[c849f608]     PHP Fatal error:  Class 'WP_Widget' not found in /var/www/affordablecolleges.com/staging/dev-sitebuild/releases/20160727225725/web/wp/wp-includes/widgets/class-wp-widget-pages.php on line 17
DEBUG[c849f608]     Fatal error: Class 'WP_Widget' not found in /var/www/affordablecolleges.com/staging/dev-sitebuild/releases/20160727225725/web/wp/wp-includes/widgets/class-wp-widget-pages.php on line 17
```

Found out that it might have something to do with Wordpress Versions 4.4+. Found this article recommending to upgrade the WP-CLI to solve this. (https://wordpress.org/support/topic/version-44-update-fatal-error-class-wp_widget-not-found) 

`bundle exec cap staging evolve:ssh` -> `wp --info`
```
PHP binary:    /usr/bin/php5
PHP version:    5.5.9-1ubuntu4.7
php.ini used:    /etc/php5/cli/php.ini
WP-CLI root dir:    phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version:    0.17.0
```

Upgraded this to by:
`curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar`
`chmod +x wp-cli.phar`
`sudo mv wp-cli.phar /usr/local/bin/wp`

Now Version is:
```
PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.7
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	0.24.0
```

`bundle exec cap staging evolve:up:db` now works

I tried reprovisioning it at first with `bundle exec cap staging evolve:provision`, but that didn't fix the issue. This was on the AffordableColleges.com staging server.

**Comment by EvanK** [comment]
Reprovisioning should fix this [as of evolution ~1.3.5](https://github.com/evolution/wordpress/commit/0847ff376937c5c352f55e99e36b9a30cbaf19af), but the site in question is still on 1.3.4. I figure that's why you had to manually correct it
