### ISSUE TITLE
Cron Directory issue

### ISSUE THREAD

**Issue by jalevin** [evolution/wordpress#148]
I started receiving failed cron job email alerts after setting up a catch-all email address for one of my projects. This 

> Cron <deploy@production> cd /var/www/mydomain.com/production/master/current/wp && /usr/local/bin/wp core is-installed --path=$PWD --url='http://production.mydomain.com/' && /usr/local/bin/wp cron event run --all --quiet --path=$PWD --url='http://production.mydomain.com/'

The directory directory should be: 
`
/var/www/mydomain.com/production/master/current/web/wp`

The command should be:

`cd /var/www/mydomain.com/production/master/current/web/wp && /usr/local/bin/wp core is-installed --path=$PWD --url='http://production.mydomain.com/' && /usr/local/bin/wp cron event run --all --quiet --path=$PWD --url='http://production.mydomain.com/'`

**Comment by jalevin** [comment]
A directive can be changed in /etc/aliases to the developer's email

#/etc/aliases
postmaster: deploy
deploy: developer@myemailaddress.com

**Comment by EvanK** [comment]
Oh dear, that's...embarrassing. I'll get this updated and released shortly

**Comment by EvanK** [comment]
Tagged & released as [v1.4.4](https://github.com/evolution/wordpress/releases/tag/v1.4.4)
