### ISSUE TITLE
Automatic WP Updates

### ISSUE THREAD

**Issue by jasoncomes** [evolution/wordpress#160]
If you go through this, Automatic Major Wordpress Update you'll notice two issues:

1. It removes my dependencies from the bower.json list, should only update the Wordpress version instance.

2. Its updating my theme folder(with probably an older release). Its only adding files that aren't there and updating files if they do exist on branch. Shouldn't touch theme folder at all.

https://github.com/HigherEducation/AccreditedOnlineColleges.org/commit/5b9337b458846298cca951ac2872b3b3a949300d

**Comment by EvanK** [comment]
I've reviewed the custom theme in question, and it does not appear to be registered in the [wordpress theme directory](https://wordpress.org/themes/) or have any custom update mechanisms built into it....so _I don't know where it is updating from_.

As a workaround, I'm going to add in the ability to _skip_ plugin and/or theme updates

**Comment by EvanK** [comment]
@jasoncomes This is addressed in the [1.6.0](https://github.com/evolution/wordpress/releases/tag/v1.6.0) tagged release.

Note that, in addition to the usual regeneration of the site, this will require:

1. removing your local `bower_components` dir & reinstalling bower deps via `bower install`
2. reprovisioning remote stages (to update the autoupdate script and cron job)
