### ISSUE TITLE
MySQL error importing non-evolution WP site

### ISSUE THREAD

**Issue by jalevin** [evolution/wordpress#163]
When importing a non-evolution wordpres 5.7.4 site I get an error from bower / mysql:

mysql stderr: ERROR 1273 (HY000) at line 4078: Unknown collation: 'utf8mb4_unicode_520_ci'

More on this [here](http://stackoverflow.com/questions/29916610/1273-unknown-collation-utf8mb4-unicode-ci-cpanel) and [here](http://anothercoffee.net/wordpress-how-to-fix-unknown-collation-error/). The new collation supports an extended utf8 character set that now includes common emojis.

MySQL 5.5 doesn't support this type of collation, however MySQL 5.6 does.

**Comment by jalevin** [comment]
Here is a PR with the fix:

https://github.com/evolution/wordpress/pull/164

**Comment by EvanK** [comment]
Resolved in #164 and released as v1.6.1
