### ISSUE TITLE
mbstring package missing for PHP7

### ISSUE THREAD

**Issue by weeirishman** [evolution/wordpress#172]
`mbstring` seems to be a common requirement for various Composer packages but the `php7` version of the package isn't part of the PHP7 upgrade.  My bad, I missed this one.

`sudo apt-get install php7.1-mbstring` should be part of the upgrade process.

**Comment by EvanK** [comment]
It looks like there are a few other packages that ubuntu's stock php5 comes with that are not included in the php7 ppa:

* bz2
* zip
* bcmath
* dba
* soap

While it's unlikely that _wordpress core_ needs any of these, I'm leaning toward explicitly installing them anyway to maintain parity
