### ISSUE TITLE
Ubuntu 18 support?

### ISSUE THREAD

**Issue by jalevin** [evolution/wordpress#182]
Hey Evan! Thanks for all your work on this project. 

Is this still active? I have a handful of projects failing due to the deprecation of Ubuntu 14.04. Is there an upgrade path for LTS 18?

Hope you're well.
J

**Comment by EvanK** [comment]
Unfortunately, there has been no active maintenance of this project for a while.

Upgrading to Ubuntu18 is probably feasible, but will require migrating to newer versions of several pieces of software in use (apache, php, varnish and pound _at least_) and is less than trivial.

**Comment by jalevin** [comment]
Haha no worries. Thanks.
