### ISSUE TITLE
Separate CLI to simpler commands?

### ISSUE THREAD

**Issue by ericclemmons** [evolution/wordpress#24]
It gets a bit cumbersome typing in:

- bundle exec cap staging evolve:ssh
- bundle exec cap staging evolve:db:up
- bundle exec cap staging provision

If there were a `evolve` CLI, it *could* be possible to do things like:

- evolve staging deploy
- evolve staging provision
- evolve production ssh
- evolve production db:up
- etc.

The question is *how*?

- How would `evolve` know what commands to run for this project (WordPress) vs. another Evolution project like Angular or React that'll use Gulp/Grunt?
- Maybe `evolve` is just a dumb passthrough, so it doesn't know what the commands are or where they're located?
- But then how would `evolve` know to prefix commands with `bundle exec cap...`?

**Comment by EvanK** [comment]
Closing this out for now
