### ISSUE TITLE
.htaccess is bare bones after initial overwrite

### ISSUE THREAD

**Issue by ericrasch** [evolution/wordpress#29]
I installed Evolve on an existing Genesis project and let it overwrite everything. When checking out the `.htaccess` file, it stripped it down to a bare-bones, initial WP-based `.htaccess`. Did we want it to do that... remove all existing Genesis WP code? In other words is this meant to be the initial `.htaccess`, without all the caching + security enhancements?

**Comment by EvanK** [comment]
This _shouldn't_ be a concern anymore, after the security/perf enhancements in #49 and the handling of old htaccess content in 6fab234
