### ISSUE TITLE
Commands like evolve:down won't work on production sites that aren't provisioned for Evolution

### ISSUE THREAD

**Issue by ericrasch** [evolution/wordpress#30]
I'm upgrading an existing Genesis-based site to Evolution. I ran `yo evolve`, then `vagrant up`, and everything is fine. When try and run `bex cap production evolve:down`, the command fails. 

It seems Evolution is trying to interact with a non-existant folder on the production site: `/var/www/website.com/production/evolve/current/web/wp-content/uploads`

The folder `/evolve/` won't exist on a non-Evolution-provisioned site. It's erroring out there and can't continue.

**Comment by EvanK** [comment]
This should be resolved with the addition of [Cambrian](https://github.com/evolution/wordpress/blob/c2d9739cc08b8978eabf410eb15152950d55cdae/docs/TUTORIAL-IMPORT.md) in 1.3.0
