### ISSUE TITLE
ssh/id_rsa files have to be manually moved on a Genesis -> Evolution migration

### ISSUE THREAD

**Issue by ericrasch** [evolution/wordpress#31]
The folder + files under `/provisioning/files/ssh` have to be manually moved to `/lib/ansible/files/ssh` when trying to migrate from Genesis to Evolution.

**Comment by EvanK** [comment]
This should be resolved with the addition of [Cambrian](https://github.com/evolution/wordpress/blob/c2d9739cc08b8978eabf410eb15152950d55cdae/docs/TUTORIAL-IMPORT.md) in 1.3.0
