### ISSUE TITLE
Existing wp-config credentials should be detected when migrating to Evolution

### ISSUE THREAD

**Issue by ericrasch** [evolution/wordpress#32]
When migrating from Genesis to Evolution, the existing `wp-config.php` credentials should be detected. The `DB_NAME`, `DB_USER`, and `DB_PASSWORD` were all overwritten when running the generator.

**Comment by EvanK** [comment]
This should be resolved with the addition of [Cambrian](https://github.com/evolution/wordpress/blob/c2d9739cc08b8978eabf410eb15152950d55cdae/docs/TUTORIAL-IMPORT.md) in 1.3.0
