### ISSUE TITLE
Existing WP files/folders should be cleaned-up when migrating

### ISSUE THREAD

**Issue by ericrasch** [evolution/wordpress#33]
Trying to migrate from Genesis to Evolution, the existing WP install files/folders were left in-place. This included the `/wp-admin` and `/wp-includes` along with all the `wp-*.php` & `xmlrpc.php` files in the root (except for the `wp-config.php file).

**Comment by EvanK** [comment]
This should be resolved with the addition of [Cambrian](https://github.com/evolution/wordpress/blob/c2d9739cc08b8978eabf410eb15152950d55cdae/docs/TUTORIAL-IMPORT.md) in 1.3.0
