### ISSUE TITLE
Can't access existing database on migration

### ISSUE THREAD

**Issue by ericrasch** [evolution/wordpress#34]
When migrating from Genesis to Evolution, Evolution seems to tack on `_local` to the database name it's trying to access (which seems to be appended outside the `wp-config.php` file), which halts WP from working.

**Comment by EvanK** [comment]
This should be resolved with the addition of [Cambrian](https://github.com/evolution/wordpress/blob/c2d9739cc08b8978eabf410eb15152950d55cdae/docs/TUTORIAL-IMPORT.md) in 1.3.0
