### ISSUE TITLE
Bring over htaccess security/performance tweaks from Genesis

### ISSUE THREAD

**Issue by EvanK** [evolution/wordpress#49]
Bring over security + performance tweaks:
> https://github.com/genesis/wordpress/blob/1e4ef9a7d72c612aabe96d8aa8d9da8a35b49610/generator/app/templates/web/htaccess#L26

There is an inherent performance penalty in htaccess configurations (searched for and loaded anew for every uncached request) vs server/vhost configs (loaded once on server re/start), so we should incorporate as much into the vhosts as possible.

**Comment by EvanK** [comment]
The `MultiViews` and `Indexes` options can be disabled in the vhost files themselves:
> https://github.com/genesis/wordpress/blob/1e4ef9a7d72c612aabe96d8aa8d9da8a35b49610/generator/app/templates/web/htaccess#L4

**Comment by EvanK** [comment]
Rewrite for blocking access to hidden files, should probably stay in htaccess:
> https://github.com/genesis/wordpress/blob/1e4ef9a7d72c612aabe96d8aa8d9da8a35b49610/generator/app/templates/web/htaccess#L49

**Comment by EvanK** [comment]
Likewise, this block of rewrites should probably stay in htaccess, but may need some refactoring since wordpress now lives in `/wp`:
> https://github.com/genesis/wordpress/blob/1e4ef9a7d72c612aabe96d8aa8d9da8a35b49610/generator/app/templates/web/htaccess#L102

**Comment by EvanK** [comment]
These `files` and `FilesMatch` directives can move to server config:
> https://github.com/genesis/wordpress/blob/1e4ef9a7d72c612aabe96d8aa8d9da8a35b49610/generator/app/templates/web/htaccess#L61

**Comment by EvanK** [comment]
The compression, etag, and expires tweaks can live in server config as well, but should be tested thoroughly to ensure they all play nice with varnish:
> https://github.com/genesis/wordpress/blob/1e4ef9a7d72c612aabe96d8aa8d9da8a35b49610/generator/app/templates/web/htaccess#L142

**Comment by EvanK** [comment]
First issue:
> https://github.com/genesis/wordpress/blob/1e4ef9a7d72c612aabe96d8aa8d9da8a35b49610/generator/app/templates/web/htaccess#L80

Prevents initial setup of wordpress (where everything redirects to `wp-admin/install.php`)

**Comment by ericrasch** [comment]
Great suggestions here. We should also review a couple of other PHP/server security issues: https://gist.github.com/ericrasch/de73853ae39666e42790

**Comment by EvanK** [comment]
![GOOD NEWS EVERYONE!](https://cloud.githubusercontent.com/assets/84145/7455356/12006b04-f241-11e4-8283-745b3e8ece3c.png)

Ubuntu 14's default PHP (5.5) already has the `pcntl_*` functions disabled and `allow_url_include` turned off!

It _should_ be safe to turn off `allow_url_fopen` and disable those other functions, but we'll have to test the default wordpress install (and probably some more common plugins) to ensure it doesn't break anything

**Comment by EvanK** [comment]
See #54
