### ISSUE TITLE
Generic Wordpress importer?

### ISSUE THREAD

**Issue by EvanK** [evolution/wordpress#57]
Rather than work on an upgrade path specifically for Genesis, I'm thinking it would be preferable to build a generic importer to work with _any_ existing wordpress site. This would be a proper successor to Genesis' "old" stage.

It should:

* fetch all files for the following (preferably via SSH but falling back to FTP when necessary, or even a local archive of the doc root?)
  * uploads
  * plugins
  * themes
* import an existing db via mysql (with/out SSH tunnel), falling back to a prepared sql dump
* start the evolution generator and let the user follow the usual prompts, then drop in all the above

Thoughts?

**Comment by jimmynotjim** [comment]
Would love this for my personal projects. Porting non-Genesis sites was always kinda tricky.

**Comment by ericrasch** [comment]
Funny enough, I find myself wanting to use Genesis for non-WP projects, as well. I really like the environment setup, but sometimes don't need WP, though Genesis required a `wp-config.php` file to be present.

**Comment by jimmynotjim** [comment]
@ericrasch ha! I've thought that too. Just having the simplicity of the packaged environments and commands to work with each makes it awesome to work with.

**Comment by EvanK** [comment]
After some discussion, I'm thinking the best solution here would consist of two pieces:

1. a wordpress plugin to install on the old site that, from an admin page, initiates a download of the wp-content and dumped db (all packaged up as a single zip/tar/gz archive)
2. a `./bin/import` script in the generated Evolution site that, given the above archive, extracts and installs any plugins, themes, uploads, and sql data into the current Evolution site

Now...to dive into the wordpress codex!

**Comment by EvanK** [comment]
I've got the export bit working (see the plugin: evolution/wordpress-plugin-cambrian@eb9e5cfca4)!

Now to write an import utility on the other side :D

**Comment by EvanK** [comment]
If you'd like to help test the export/import process, the first step is to install the [Cambrian Explosion](https://dl.dropboxusercontent.com/u/56187/cambrian.zip) plugin in the existing Wordpress site that you'd like to port over. Activate and run the plugin, and it will download a zipfile of your site content.

Next, you'll need to pull the importer branch down to your local Yeoman cache:

```bash
# remove any existing evolution from yeoman cache
mkdir -p ~/.cache/yeoman/evolution/wordpress
rm -rf ~/.cache/yeoman/evolution/wordpress/v1.*

# clone latest evolution into yeoman cache
git clone https://github.com/evolution/wordpress.git ~/.cache/yeoman/evolution/wordpress/v1.1.3

# cd to cloned codebase, checkout importer branch and install npm deps
cd ~/.cache/yeoman/evolution/wordpress/v1.1.3
git checkout 57-cambrian-importer
npm install
```

Finally, you'll want to generate a new Evolution site into which you'll import the zipfile of your old site's content:

```bash
# create and cd to directory for new Evolution site
mkdir ~/Sites/SomeTestSite.com
cd ~/Sites/SomeTestSite.com

# generate and prepare a new site
yo evolve wordpress
vagrant up

# invoke the importer
./bin/import
```

**Comment by EvanK** [comment]
Aaaand I forgot a step, before the `vagrant up`:

```bash
# copy checked out evolution branch to generated site's bower components
cp -r ~/.cache/yeoman/evolution/wordpress/v1.1.3/ ~/Sites/SomeTestSite.com/bower_components/evolution-wordpress/
```

**Comment by jimmynotjim** [comment]
Sweet! Going to give this a shot this weekend and will report back.

**Comment by EvanK** [comment]
Closing this issue, please see #66
