### ISSUE TITLE
lib/wordpress/Evolution.php missing from v1.0.16 ?

### ISSUE THREAD

**Issue by mcheck** [evolution/wordpress#63]
I have a staging server to which I deployed today and it suddenly broke because pulling 1.0.16 removed the ```lib/wordpress/Evolution.php```. Was this intentional, or part of a bigger plan that has not changed?

And that brings me to a related item: when deploying to a server, why does the post install run a bower install with a carat range for the evolution-wordpress which seems like it could potentially put the local dev machine and the remote server out of sync for dependencies, first of all. And second, that bump in version seem like it might break something unexpectedly. Is there something bigger I'm missing here about deploying and running the ```bower installs```?

**Comment by EvanK** [comment]
`Evolution.php` was moved from the bower-included dependency to the generated site itself. That was a potentially breaking change, and it _should_ have warranted a minor version bump. My mistake.

You're also right about the carat version in bower, it should be `~version`. The intention here is to allow patch level changes (like non-breaking bugfixes) to go out with new deployments automatically.

The upgrade path across minor versions (eg, `1.0.16` to `1.1.0`) will be to re-run the generator against your existing codebase, which should update whatever files have changed.

I'm working on a fix for this, and a minor version bump...will note here when it's out. Thanks!

**Comment by mcheck** [comment]
Thanks Evan. If I can help, please let me know. I've received quite a bit from genesis and evolution and I'm happy to give back where I can.

**Comment by EvanK** [comment]
Much appreciated, as is your being a patient test subject for us!

The fix is out, so you can update your site by re-running the generator against it

**Comment by mcheck** [comment]
Thanks, simply a ```yo evolution wordpress```? I haven't updated a site
before without adjusting the ```bower.json``` file where I wanted the
versions and then ```bower update```

**Comment by EvanK** [comment]
It would be `yo evolve wordpress`, and the generator will take a moment on start to fetch the latest version (1.1.0).

From there, the prompts _should_ pick up and default to your existing configuration. It should also default to _not_ regenerating your ssh keys or ssl certs.

**Comment by mcheck** [comment]
Ok, rolling the dice... :)  Will let you know.
ᐧ
