### ISSUE TITLE
Documentation request: List files to change if server is named differently

### ISSUE THREAD

**Issue by germanny** [evolution/wordpress#71]
Would you add to the documentation that if a server is named differently than the out-of-the-box evolution core expects, such as `production.server.com` is named `new.server.com` or something like that, that these files should be updated to reflect the proper server name: 

* `lib/capistrano/deploy/production.rb`
* 'lib/ansible/hosts'

**Comment by mcheck** [comment]
Hi there,
Also `web/.htaccess`
For security and spidering.

**Comment by EvanK** [comment]
The [Cambrian](https://github.com/evolution/wordpress/blob/c2d9739cc08b8978eabf410eb15152950d55cdae/docs/TUTORIAL-IMPORT.md) importer _should_ remove the need for non-standard server entries for capistrano and ansible, that (as I understand) were part of upgrading by hand?
