### ISSUE TITLE
SSL Certificate does not belong to download.suhosin.org.  Make sure the url has a certificate that belongs to it or use validate_certs=False (insecure)

### ISSUE THREAD

**Issue by brainwarped** [evolution/wordpress#91]
http://docs.ansible.com/ansible/get_url_module.html

Solution: bower_components/evolution-wordpress/lib/ansible/roles/php-hardened/tasks/build.yml line 3:

`get_url:        url={{ suhosin.url }} dest=/tmp/src-suhosin.tar.gz validate_certs=no`

**Comment by EvanK** [comment]
This should be fixed in 9fef3ab, and as of tag v1.3.2.

Thanks for the feedback!
